/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.app.App
import org.example.app.Fecha

fun main() {
    val date = Fecha(14, 5, 2010)
    println(date)
}
